### ISSUE TITLE
pan & pitch?

### ISSUE THREAD

**Issue by semivori** [DummyEkko/vue3-zoom-pan-pinch#1]
I can zoom with the mouse wheel but how can I pan and pitch?

**Comment by DummyEkko** [comment]
these two features are under development

**Comment by DummyEkko** [comment]
> I can zoom with the mouse wheel but how can I pan and pitch?

these two features are under development

**Comment by semivori** [comment]
> these two features are under development

I'll wait

**Comment by semivori** [comment]
@DummyEkko
the cursor is not fixed when zooming in again https://i.imgur.com/PwaQS4M.gif
but yesterday it was working fine https://i.imgur.com/MnQCMQA.gif

**Comment by DummyEkko** [comment]
> @DummyEkko the cursor is not fixed when zooming in again https://i.imgur.com/PwaQS4M.gif but yesterday it was working fine https://i.imgur.com/MnQCMQA.gif

newPositionX and newPositionY were calculated wrong

`
    const newPositionX = -(mouseX *(newScale - scale)) + positionX;
    const newPositionY = -(mouseY * (newScale - scale)) + positionY;
`

I'll update later

**Comment by semivori** [comment]
@DummyEkko it works wrong in the next case https://i.imgur.com/ldFw3AG.gif
example code https://pastebin.com/2ipP3hSB
